# TASK -2 Clean_Data

In [ ]:

import pandas as pd 
import numpy as np 

# Load churnguard_data.csv
df = pd.read_csv("churnguard_data.csv")

# Drop the customerID column
df = df.drop(["customerID"] , axis = 1)

# Remove duplicate rows
df = df.drop_duplicates()
print(df.duplicated().sum())

# Strip whitespace from gender and PaymentMethod using .str.strip()
cols_del_whitespace = ["gender" , "PaymentMethod"]
df[cols_del_whitespace] = df[cols_del_whitespace].apply(lambda x: x.str.strip())
df["PhoneService"].unique()

# Standardise casing — convert Churn, PhoneService, and PaperlessBilling to title case using .str.strip().str.title()


# Fix Contract — map all variations to one of three valid values:
# Month-to-month, One year, Two year
# Fix InternetService — map all variations to one of three valid values:
# DSL, Fiber optic, No
# Fix TotalCharges — convert to numeric using pd.to_numeric(..., errors='coerce') so junk becomes NaN
# Remove rows where tenure is zero or negative
# Remove rows where MonthlyCharges is less than 10 or greater than 200
# Fill missing values:
# MonthlyCharges → column mean
# TotalCharges → column mean
# tenure → column median (use integer rounding)
# Print the shape of the cleaned DataFrame
# Print missing value counts to confirm all issues are resolved

0

<StringArray>
['YES', 'Yes', 'yes', 'No', 'yEs', 'no', 'nO', 'NO']
Length: 8, dtype: str

In [26]:
df

,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,21.0,YES,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,Male,0,55.0,YES,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,Female,1,63.0,Yes,Fiber optic,Month-to-month,YES,Mailed check,56.97,3641.3,Yes
4,Female,0,8.0,Yes,DSl,month to month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...
1025,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.4,No
1027,Male,1,69.0,Yes,DSl,Two year,Yes,Electronic check,95.00,6689.62,No
1028,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.2,No
1029,Female,0,49.0,Yes,DSL,month-to-month,No,Credit card,103.84,5307.47,No

In [22]:
df["InternetService"].unique()

KeyError: 'InternetService'

In [13]:
df

,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,21.0,YES,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,Male,0,55.0,YES,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,Female,1,63.0,Yes,Fiber optic,Month-to-month,YES,Mailed check,56.97,3641.3,Yes
4,Female,0,8.0,Yes,DSl,month to month,No,Electronic check,39.69,309.79,Yes
...,...,...,...,...,...,...,...,...,...,...,...
1025,Female,0,26.0,Yes,DSL,One year,Yes,Electronic check,51.68,1369.73,No
1026,Male,0,49.0,Yes,Fiber optic,Two year,Yes,Electronic check,85.39,4305.4,No
1027,Male,1,69.0,Yes,DSl,Two year,Yes,Electronic check,95.00,6689.62,No
1028,Female,1,3.0,Yes,No,Two year,Yes,Electronic check,25.08,77.2,No
1029,Female,0,49.0,Yes,DSL,month-to-month,No,Credit card,103.84,5307.47,No